function_documentation.Rmd:
  path: dev/function_documentation.Rmd
  state: active
  R:
  - R/plot_top10_by_country_and_year.R
  - R/run_app.R
  tests:
  - tests/testthat/test-plot_top10_by_country_and_year.R
  - tests/testthat/test-run_app.R
  vignettes: vignettes/development.Rmd
  inflate:
    flat_file: dev/function_documentation.Rmd
    vignette_name: Development
    open_vignette: true
    check: true
    document: true
    overwrite: ask
