---
title: "Function documentation"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

<!--
 For each fo the function you need, add FUSEN chunk through the Rstudio add-in " add {fusen} chunks"
 -->

# plot_top10_by_country_and_year
    
```{r function-plot_top10_by_country_and_year}
#' Create a plot with top10 country of orgin for Refugees and OIP per country of asylum and year
#'
#' @param year a numeric value for the year
#' @param countryname the name of the country of asulum
#'
#' @return a ggplot2 with UNHCR brand
#' 
#' @import unhcrthemes
#' @import ggplot2
#' @import refugees
#' @import dplyr
#' @importFrom stringr str_wrap
#' @importFrom stats reorder
#' @importFrom extrafont font_import loadfonts
#' @export

plot_top10_by_country_and_year <- function( year,   
                                            countryname) {  


# extrafont::font_import(pattern = 'Lato', prompt = FALSE)
# extrafont::loadfonts(device = "all", quiet = TRUE)

plot <- refugees::population |>
  filter(year == year &  
           coa_name == countryname) |>  
  summarise( refugees = sum(refugees, na.rm = TRUE) + 
               sum(oip, na.rm = TRUE),
    .by = coo_name ) |>
  slice_max(order_by = refugees, n = 10) |>
  mutate(coo_name = str_wrap(coo_name, 25)) |>
  ggplot(  aes( x = refugees, y = reorder(coo_name, refugees))) +
  geom_col( fill = unhcr_pal(n = 1, "pal_blue"), width = 0.8) +
  scale_x_continuous(
    expand = expansion(mult = c(0, .1)),
    breaks = seq(0, 7e6, by = 1e6),
    labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
  labs(
    title = paste0("Refugees and other people in need of international protection in ",countryname),  
    subtitle =  paste0("By country of origin at the end of ", year),  
     caption = "Source: Refugee Data Finder<br>\u00a9 UNHCR, The UN Refugee Agency",
    x = "Number of people"
  ) +
  theme_unhcr(grid = "X", axis = "Y", axis_title = "X")

return(plot)
  
}
```
  
```{r example-plot_top10_by_country_and_year}
plot_top10_by_country_and_year( year = 2022, 
                                 countryname = "Peru")
```
  
```{r tests-plot_top10_by_country_and_year}
test_that("plot_top10_by_country_and_year works", {
  expect_true(inherits(plot_top10_by_country_and_year, "function")) 
})
```
  


<!--
 below is a default chunk to create and document your run_app function
-->

# run_app


<!--
Create a chunk for the core of the function

- The chunk needs to be named `function` at least
- It contains the code of a documented function
- The chunk can also be named `function-my_function` to make it easily
findable in your Rmd
- Let the `@examples` part empty, and use the next `examples` chunk instead to present reproducible examples

After inflating the template

-  This function code will automatically be added in a new file in the "R/" directory
-->
    
```{r function-run_app}
#' Run the Shiny Application
#' 
#' 
#' @param onStart A function that will be called before the app is actually run.
#' This is only needed for \code{shinyAppObj}, since in the \code{shinyAppDir}
#' case, a \code{global.R} file can be used for this purpose.

#' @param options Named options that should be passed to the \code{runApp} call
#' (these can be any of the following: "port", "launch.browser", "host", "quiet",
#' "display.mode" and "test.mode"). You can also specify \code{width} and
#' \code{height} parameters which provide a hint to the embedding environment
#' about the ideal height/width for the app.

#' @param enableBookmarking Can be one of \code{"url"}, \code{"server"}, or
#' \code{"disable"}. The default value, \code{NULL}, will respect the setting from
#' any previous calls to  \code{\link[shiny:enableBookmarking]{enableBookmarking()}}. See 
#' #' \code{\link[shiny:enableBookmarking]{enableBookmarking()}}
#' for more information on bookmarking your app.

#' @param uiPattern A regular expression that will be applied to each \code{GET}
#' request to determine whether the \code{ui} should be used to handle the
#' request. Note that the entire request path must match the regular
#' expression in order for the match to be considered successful.
#' 
#' 
#' @param ... arguments to pass to golem_opts.
#' See `?golem::get_golem_options` for more details.
#'
#' @importFrom shiny shinyApp
#' @importFrom golem with_golem_options
#' 
#' @return a shiny app
#' 
#' @export

run_app <- function(
    onStart = NULL,
    options = list(),
    enableBookmarking = NULL,
    uiPattern = "/",
    ...
) {
  with_golem_options(
    app = shinyApp(
      ui = app_ui,
      server = app_server,
      onStart = onStart,
      options = options,
      enableBookmarking = enableBookmarking,
      uiPattern = uiPattern
    ),
    golem_opts = list(...)
  )
}

```

<!--
Create a chunk with an example of use for your function

- The chunk needs to be named `examples` at least
- It contains working examples of your function
- The chunk is better be named `examples-my_median` to be handled
correctly when inflated as a vignette

After inflating the template

-  This example will automatically be added in the '@examples' part of our function above in the "R/" directory
- This example will automatically be added in the vignette created from this Rmd template
-->

```{r example-run_app}
# run_app()
```

<!--
Create a chunk with a test of use for your function

- The chunk needs to be named `tests` at least
- It contains working tests of your function
- The chunk is better be named `tests-my_median` to be handled
correctly when inflated as a vignette

After inflating the template

-  This test code will automatically be added in the "tests/testthat/" directory
-->
 
```{r tests-run_app}
# test_that("run_app works", {
#   expect_true(inherits(run_app, "function")) 
# })
```
  



<!--
 Once you have created your back office functions , run the next chunk to install and package them

# There can be development actions

Create a chunk with 'development' actions

- The chunk needs to be named `development` or `dev`
- It contains functions that are used for package development only
- Note that you may want to store most of these functions in the 0-dev_history.Rmd file

These are only included in the present flat template file, their content will not be part of the package anywhere else.
-->

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/function_documentation.Rmd", vignette_name = "Development")
```

