# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

test_that("plot_top10_by_country_and_year works", {
  expect_true(inherits(plot_top10_by_country_and_year, "function")) 
})
