# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' Create a plot with top10 country of orgin for Refugees and OIP per country of asylum and year
#'
#' @param year a numeric value for the year
#' @param countryname the name of the country of asulum
#'
#' @return a ggplot2 with UNHCR brand
#' 
#' @import unhcrthemes
#' @import ggplot2
#' @import refugees
#' @import dplyr
#' @importFrom stringr str_wrap
#' @importFrom stats reorder
#' @importFrom extrafont font_import loadfonts
#' @export
#' @examples
#' plot_top10_by_country_and_year( year = 2022, 
#'                                  countryname = "Peru")

plot_top10_by_country_and_year <- function( year,   
                                            countryname) {  


# extrafont::font_import(pattern = 'Lato', prompt = FALSE)
# extrafont::loadfonts(device = "all", quiet = TRUE)

plot <- refugees::population |>
  filter(year == year &  
           coa_name == countryname) |>  
  summarise( refugees = sum(refugees, na.rm = TRUE) + 
               sum(oip, na.rm = TRUE),
    .by = coo_name ) |>
  slice_max(order_by = refugees, n = 10) |>
  mutate(coo_name = str_wrap(coo_name, 25)) |>
  ggplot(  aes( x = refugees, y = reorder(coo_name, refugees))) +
  geom_col( fill = unhcr_pal(n = 1, "pal_blue"), width = 0.8) +
  scale_x_continuous(
    expand = expansion(mult = c(0, .1)),
    breaks = seq(0, 7e6, by = 1e6),
    labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
  labs(
    title = paste0("Refugees and other people in need of international protection in ",countryname),  
    subtitle =  paste0("By country of origin at the end of ", year),  
     caption = "Source: Refugee Data Finder<br>\u00a9 UNHCR, The UN Refugee Agency",
    x = "Number of people"
  ) +
  theme_unhcr(grid = "X", axis = "Y", axis_title = "X")

return(plot)
  
}
